
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    first VARCHAR(255) NOT NULL,
    last VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


DROP TABLE IF EXISTS signatures CASCADE;
CREATE TABLE signatures(
    id SERIAL PRIMARY KEY,
    user_id SMALLINT REFERENCES users,
    sign TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS user_profiles CASCADE;

CREATE TABLE user_profiles(
    id SERIAL PRIMARY KEY,
    user_id SMALLINT REFERENCES users,
    age SMALLINT DEFAULT null,
    city VARCHAR(255),
    homepage VARCHAR(255)
);
